"use client";

import { ArrowClockwise, Clipboard, DownloadSimple, FileText, Flask, MagnifyingGlass, Scales, X } from "@phosphor-icons/react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ApiClientError, cancelBatchJob, downloadBatchExport, downloadFilteredBatchExport, fetchBatchJob, fetchEndpoints, resolveCompound } from "@/lib/api";
import type { BatchJob, BatchResultRow, CompoundResponse, EndpointMetadata, JsonValue } from "@/lib/types";
import { ScientificDisclaimer } from "./scientific-disclaimer";
import { ValidationSummary } from "./validation-summary";
import { WorkflowStepper } from "./workflow-stepper";
import { registerAssistantCapabilities } from "@/lib/assistant-capabilities";
import type { UIAction } from "@/lib/agent-types";
import { clearHighlight } from "./assistant/assistant-action-transition";
import { publishAssistantPageContext } from "@/lib/assistant-page-state";
import { useAssistant } from "@/contexts/assistant-provider";

function endpointValue(row: BatchResultRow, key: string): JsonValue | undefined {
  for (const category of Object.values(row.predictions ?? {})) if (key in category) return category[key];
}
function displayValue(value: JsonValue | undefined): string { return value === undefined || value === null ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value); }
function terminal(status: BatchJob["status"]) { return ["completed", "completed_with_errors", "failed", "cancelled"].includes(status); }

export function BatchJobWorkspace({ jobId }: { jobId: string }) {
  const { open: assistantOpen, closing: assistantClosing } = useAssistant();
  const [job, setJob] = useState<BatchJob | null>(null); const [registry, setRegistry] = useState<Record<string, EndpointMetadata>>({});
  const [error, setError] = useState<string | null>(null); const [search, setSearch] = useState("");
  const [validationFilter, setValidationFilter] = useState("all"); const [predictionFilter, setPredictionFilter] = useState("all");
  const [selectedEndpoints, setSelectedEndpoints] = useState<string[]>([]);
  const [selectedRow, setSelectedRow] = useState<number | null>(null); const [selectedForCompare, setSelectedForCompare] = useState<number[]>([]);
  const [compound, setCompound] = useState<CompoundResponse | null>(null); const [showDetail, setShowDetail] = useState(false); const [showComparison, setShowComparison] = useState(false);
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [rangeMin, setRangeMin] = useState(""); const [rangeMax, setRangeMax] = useState("");
  const [highlightedTarget, setHighlightedTarget] = useState<string | null>(null);

  const acceptJob = useCallback((value: BatchJob) => { setJob(value); setError(null); const keys = Array.from(new Set(value.rows.flatMap((row) => Object.values(row.predictions ?? {}).flatMap((group) => Object.keys(group))))); setSelectedEndpoints((current) => current.length ? current.filter((key) => keys.includes(key)) : keys.slice(0, 3)); setSelectedRow((current) => current ?? value.rows.find((row) => row.canonical_smiles)?.row_number ?? null); }, []);
  const refresh = useCallback(async () => { try { acceptJob(await fetchBatchJob(jobId)); } catch (caught) { setError(caught instanceof ApiClientError ? caught.message : "The batch job could not be loaded."); } }, [acceptJob, jobId]);
  useEffect(() => { fetchBatchJob(jobId).then(acceptJob).catch((caught) => setError(caught instanceof ApiClientError ? caught.message : "The batch job could not be loaded.")); fetchEndpoints().then((value) => setRegistry(value.endpoints)).catch(() => undefined); }, [acceptJob, jobId]);
  useEffect(() => { if (!job || terminal(job.status)) return; const id = window.setInterval(() => void refresh(), 1000); return () => window.clearInterval(id); }, [job, refresh]);
  const endpointKeys = useMemo(() => Array.from(new Set((job?.rows ?? []).flatMap((row) => Object.values(row.predictions ?? {}).flatMap((group) => Object.keys(group))))), [job]);
  const selected = job?.rows.find((row) => row.row_number === selectedRow) ?? null;
  useEffect(() => { if (!selected?.canonical_smiles) return; resolveCompound(selected.canonical_smiles).then(setCompound).catch(() => undefined); }, [selected?.canonical_smiles]);
  const filtered = useMemo(() => (job?.rows ?? []).filter((row) => {
    const haystack = `${row.compound_id ?? ""} ${row.compound_name ?? ""} ${row.input_smiles}`.toLowerCase();
    if (search && !haystack.includes(search.toLowerCase())) return false;
    if (validationFilter !== "all" && row.validation_status !== validationFilter) return false;
    if (predictionFilter !== "all" && row.prediction_status !== predictionFilter) return false;
    const rangeKey = selectedEndpoints[0]; const value = rangeKey ? endpointValue(row, rangeKey) : undefined;
    if (rangeMin && (typeof value !== "number" || value < Number(rangeMin))) return false;
    if (rangeMax && (typeof value !== "number" || value > Number(rangeMax))) return false;
    return true;
  }), [job, search, validationFilter, predictionFilter, selectedEndpoints, rangeMin, rangeMax]);
  useEffect(() => publishAssistantPageContext({ page: "batch", batch_job_id: jobId, selected_compound_ids: selectedForCompare.map((number) => job?.rows.find((row) => row.row_number === number)?.compound_id).filter((value): value is string => Boolean(value)), selected_row_numbers: selectedForCompare.length ? selectedForCompare : selectedRow ? [selectedRow] : [], selected_endpoints: selectedEndpoints, validation_filter: validationFilter, prediction_filter: predictionFilter, search_query: search, range_endpoint: selectedEndpoints[0] ?? null, range_min: rangeMin ? Number(rangeMin) : null, range_max: rangeMax ? Number(rangeMax) : null, active_view: showComparison ? "comparison" : showDetail ? "compound_detail" : "results", comparison_open: showComparison, detail_open: showDetail, current_page: page, page_size: pageSize, total_row_count: job?.rows.length ?? null, filtered_row_count: filtered.length, visible_row_numbers: filtered.slice((page - 1) * pageSize, page * pageSize).map((row) => row.row_number) }), [job, jobId, selectedForCompare, selectedRow, selectedEndpoints, validationFilter, predictionFilter, search, rangeMin, rangeMax, showComparison, showDetail, page, pageSize, filtered]);
  useEffect(() => registerAssistantCapabilities(`/batch/${jobId}`, { execute(action: UIAction) {
    if (!job) throw new Error("job unavailable");
    if (action.type === "SET_BATCH_FILTERS") { if (typeof action.payload.validation_status === "string") setValidationFilter(action.payload.validation_status); if (typeof action.payload.prediction_status === "string") setPredictionFilter(action.payload.prediction_status); setPage(1); setHighlightedTarget("batch-results"); clearHighlight(setHighlightedTarget); return { targetId: "batch-results", message: action.payload.prediction_status === "failed" ? "Showing failed rows" : "Batch filters applied" }; }
    if (action.type === "SELECT_BATCH_ROW") { const row = action.payload.target === "first-failed" ? job.rows.find((item) => item.prediction_status === "failed") : job.rows.find((item) => String(item.row_number) === action.payload.target); if (!row) throw new Error("row missing"); setSelectedRow(row.row_number); setHighlightedTarget(`batch-row-${row.row_number}`); clearHighlight(setHighlightedTarget); return { targetId: `batch-row-${row.row_number}`, message: `Selected row ${row.row_number}` }; }
    if (action.type === "OPEN_BATCH_JOB") return { targetId: "batch-job", message: "Batch job opened" };
    if (action.type === "SET_BATCH_SEARCH") { setSearch(String(action.payload.query ?? "")); setPage(1); return { targetId: "batch-results", message: "Batch search applied" }; }
    if (action.type === "SET_BATCH_ENDPOINTS") { const keys = action.payload.endpoints as string[]; if (!keys.every((key) => endpointKeys.includes(key))) throw new Error("unknown endpoint"); setSelectedEndpoints(keys); return { targetId: "batch-results", message: "Endpoint columns updated" }; }
    if (action.type === "SET_BATCH_RANGE") { const endpoint = String(action.payload.endpoint); if (!endpointKeys.includes(endpoint)) throw new Error("unknown endpoint"); setSelectedEndpoints((current) => [endpoint, ...current.filter((key) => key !== endpoint)]); setRangeMin(action.payload.minimum == null ? "" : String(action.payload.minimum)); setRangeMax(action.payload.maximum == null ? "" : String(action.payload.maximum)); setPage(1); return { targetId: "batch-results", message: "Endpoint range applied" }; }
    if (action.type === "SELECT_BATCH_ROWS") { const numbers = action.payload.row_numbers as number[]; if (!numbers.every((number) => job.rows.some((row) => row.row_number === number))) throw new Error("row missing"); if (action.payload.purpose === "comparison") { if (numbers.some((number) => job.rows.find((row) => row.row_number === number)?.prediction_status !== "completed")) throw new Error("row incomplete"); setSelectedForCompare(numbers); } setSelectedRow(numbers[0]); return { targetId: `batch-row-${numbers[0]}`, message: `${numbers.length} batch rows selected` }; }
    if (action.type === "OPEN_BATCH_COMPARISON") { setShowComparison(true); return { targetId: "batch-comparison", message: "Neutral comparison opened" }; }
    if (action.type === "EXPORT_BATCH_VIEW") { const kind = String(action.payload.kind); if (kind === "filtered") void downloadFilteredBatchExport(job.job_id, filtered.map((row) => row.row_number)); else if (["results", "errors", "metadata"].includes(kind)) void downloadBatchExport(job.job_id, kind as "results" | "errors" | "metadata"); else throw new Error("export unavailable"); return { targetId: "batch-results", message: "Batch export prepared" }; }
    throw new Error("unsupported batch action");
  }}), [job, jobId, endpointKeys, filtered, selectedForCompare]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const visibleRows = filtered.slice((page - 1) * pageSize, page * pageSize);
  function toggleCompare(row: BatchResultRow) { if (row.prediction_status !== "completed") return; setSelectedForCompare((current) => current.includes(row.row_number) ? current.filter((id) => id !== row.row_number) : current.length < 5 ? [...current, row.row_number] : current); }
  const progress = job && job.progress.total ? Math.round(job.progress.processed / job.progress.total * 100) : 0;

  if (error) return <section className="batch-fatal" role="alert"><h2>Batch job unavailable</h2><p>{error}</p><Link className="secondary-action" href="/batch">Start a new batch</Link></section>;
  if (!job) return <section className="batch-fatal" role="status"><Flask size={34} weight="duotone" /><h2>Loading batch job</h2></section>;
  return <div className={`batch-job-workspace ${assistantOpen && !assistantClosing ? "has-docked-assistant" : ""}`} aria-live="polite">
    <div className="batch-step-progress"><WorkflowStepper current={4} /><section className="prediction-progress"><span><b>Prediction progress</b><strong>{progress}%</strong></span><p>{job.progress.processed} / {job.progress.total} unique molecules · {job.progress.completed} completed · {job.progress.failed} failed</p><progress max={job.progress.total || 1} value={job.progress.processed} /></section></div>
    {job.prediction_mode === "mock" ? <p className="mock-warning">Development mode: results are deterministic interface fixtures and were not generated by the real ADMET-AI model.</p> : null}
    <div className="batch-review-layout">
      <aside className="batch-job-overview"><h2>Batch Job Overview</h2><dl>{[["File name", job.source_filename], ["File type", job.file_type.toUpperCase()], ["Total rows", job.summary.total_rows], ["Prediction mode", job.prediction_mode], ["Job status", job.status.replaceAll("_", " ")], ["Valid molecules", job.summary.valid_molecules], ["Unique valid molecules", job.summary.unique_valid_molecules], ["Job ID", job.job_id], ["Created", new Date(job.created_at).toLocaleString()]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd className={label === "Job ID" ? "mono" : ""}>{value}</dd></div>)}</dl><div className="overview-actions"><button className="secondary-action" onClick={() => void downloadBatchExport(job.job_id, "metadata")}><FileText size={17} /> Job metadata</button><button className="secondary-action" onClick={() => void refresh()}><ArrowClockwise size={17} /> Refresh</button>{job.status === "running" ? <button className="secondary-action danger-action" onClick={() => void cancelBatchJob(job.job_id).then(setJob)}><X size={17} /> Cancel job</button> : null}</div></aside>
      <section className={`batch-results-region ${highlightedTarget === "batch-results" ? "assistant-target-highlight" : ""}`} data-assistant-target="batch-results">
        <ValidationSummary summary={job.summary} />
        <div className="results-toolbar"><label className="search-control"><MagnifyingGlass size={17} /><span className="visually-hidden">Search compounds</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search compounds" /></label><label><span className="visually-hidden">Filter validation status</span><select value={validationFilter} onChange={(event) => setValidationFilter(event.target.value)}><option value="all">All validation</option><option value="valid">Valid</option><option value="duplicate">Duplicate</option><option value="invalid_smiles">Invalid SMILES</option><option value="missing_smiles">Missing SMILES</option></select></label><label><span className="visually-hidden">Filter prediction status</span><select value={predictionFilter} onChange={(event) => setPredictionFilter(event.target.value)}><option value="all">All predictions</option><option value="completed">Completed</option><option value="failed">Failed</option><option value="pending">Pending</option></select></label><details className="endpoint-selector"><summary>Select endpoints</summary><div>{endpointKeys.length ? endpointKeys.map((key) => <label key={key}><input type="checkbox" checked={selectedEndpoints.includes(key)} onChange={() => setSelectedEndpoints((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key])} /> {registry[key]?.display_name ?? key}</label>) : <p>Endpoints appear after prediction completes.</p>}</div></details><label className="range-control"><span>Range</span><input aria-label="Minimum endpoint value" type="number" placeholder="Min" value={rangeMin} onChange={(event) => setRangeMin(event.target.value)} /><input aria-label="Maximum endpoint value" type="number" placeholder="Max" value={rangeMax} onChange={(event) => setRangeMax(event.target.value)} /></label><button className="secondary-action" disabled={selectedForCompare.length < 2} onClick={() => setShowComparison(true)}><Scales size={17} /> Compare ({selectedForCompare.length})</button><button className="secondary-action" onClick={() => void downloadBatchExport(job.job_id, "results")}><DownloadSimple size={17} /> Results</button><button className="secondary-action" onClick={() => void downloadBatchExport(job.job_id, "errors")}><DownloadSimple size={17} /> Errors</button></div>
        <div className="table-scroll batch-results-table"><table><thead><tr><th><span className="visually-hidden">Compare</span></th><th>Row</th><th>Compound ID</th><th>Compound name</th><th>Input SMILES</th><th>Canonical SMILES</th><th>Validation</th><th>Prediction</th>{selectedEndpoints.map((key) => <th key={key} title={key}>{registry[key]?.display_name ?? key}{registry[key]?.unit_verified && registry[key]?.unit ? <small>{registry[key].unit}</small> : null}</th>)}</tr></thead><tbody>{visibleRows.map((row) => <tr key={row.row_number} data-assistant-target={`batch-row-${row.row_number}`} className={`${selectedRow === row.row_number ? "selected" : ""} ${highlightedTarget === `batch-row-${row.row_number}` ? "assistant-target-highlight" : ""}`} onClick={() => setSelectedRow(row.row_number)}><td><input aria-label={`Compare row ${row.row_number}`} type="checkbox" disabled={row.prediction_status !== "completed"} checked={selectedForCompare.includes(row.row_number)} onChange={() => toggleCompare(row)} onClick={(event) => event.stopPropagation()} /></td><td>{row.row_number}</td><td>{row.compound_id ?? "—"}</td><td>{row.compound_name ?? "—"}</td><td><code>{row.input_smiles || "—"}</code></td><td><code>{row.canonical_smiles ?? "—"}</code></td><td><span className={`app-status status-${row.validation_status}`}>{row.validation_status.replaceAll("_", " ")}</span></td><td><span className={`app-status status-${row.prediction_status}`}>{row.prediction_status.replaceAll("_", " ")}</span></td>{selectedEndpoints.map((key) => <td className="numeric" key={key}>{displayValue(endpointValue(row, key))}{registry[key]?.unit_verified && registry[key]?.unit ? ` ${registry[key].unit}` : ""}</td>)}</tr>)}</tbody></table></div>
        <footer className="table-pagination"><span>Showing {visibleRows.length} of {filtered.length} rows</span><label>Rows per page <select value={pageSize} onChange={(event) => setPageSize(Number(event.target.value))}><option>10</option><option>25</option><option>50</option></select></label><div><button aria-label="Previous page" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>‹</button><span>Page {page} of {pageCount}</span><button aria-label="Next page" disabled={page === pageCount} onClick={() => setPage((value) => value + 1)}>›</button></div></footer>
      </section>
      <aside className="compound-preview"><h2>Selected Compound Preview</h2>{selected ? <>{compound ? <div className="batch-structure" role="img" aria-label={`2D structure for ${selected.compound_name ?? selected.compound_id ?? `row ${selected.row_number}`}`} dangerouslySetInnerHTML={{ __html: compound.depiction_svg }} /> : <div className="batch-structure"><span>Structure unavailable</span></div>}<dl><div><dt>Compound ID</dt><dd>{selected.compound_id ?? "Not provided"}</dd></div><div><dt>Name</dt><dd>{selected.compound_name ?? "Not provided"}</dd></div><div><dt>Prediction</dt><dd>{selected.prediction_status}</dd></div><div><dt>Canonical SMILES</dt><dd className="smiles-preview"><code>{selected.canonical_smiles ?? "Not available"}</code>{selected.canonical_smiles ? <button aria-label="Copy canonical SMILES" onClick={() => navigator.clipboard.writeText(selected.canonical_smiles!)}><Clipboard size={16} /></button> : null}</dd></div></dl><h3>Selected endpoints</h3><ul className="preview-endpoints">{selectedEndpoints.slice(0, 5).map((key) => <li key={key}><span>{registry[key]?.display_name ?? key}</span><code>{displayValue(endpointValue(selected, key))}</code></li>)}</ul><button className="secondary-action" onClick={() => setShowDetail((value) => !value)}>{showDetail ? "Close full detail" : "Open full detail"}</button></> : <p>Select a row to inspect its identity and results.</p>}</aside>
    </div>
    {showDetail && selected ? <section className="batch-detail-panel"><header><div><span className="stage-kicker">Compound detail</span><h2>{selected.compound_name ?? selected.compound_id ?? `Row ${selected.row_number}`}</h2></div><button className="icon-button" aria-label="Close compound detail" onClick={() => setShowDetail(false)}><X size={20} /></button></header><p>{selected.summary ?? selected.error_message ?? "Prediction details are not available for this row."}</p>{selected.predictions ? Object.entries(selected.predictions).map(([category, values]) => <section key={category}><h3>{category.replaceAll("_", " ")}</h3><dl>{Object.entries(values).map(([key, value]) => <div key={key}><dt><code>{key}</code><small>{registry[key]?.display_name}{registry[key]?.output_type_label ? ` · ${registry[key].output_type_label}` : " · Metadata not verified"}</small></dt><dd>{displayValue(value)}{registry[key]?.unit_verified && registry[key]?.unit ? ` ${registry[key].unit}` : ""}</dd></div>)}</dl></section>) : null}<details><summary>Raw row output</summary><pre>{JSON.stringify(selected, null, 2)}</pre></details></section> : null}
    {showComparison ? <section className="comparison-panel"><header><div><span className="stage-kicker">Neutral comparison</span><h2>Selected compounds</h2><p>Raw model outputs are shown side by side without an overall ranking.</p></div><button className="icon-button" aria-label="Close comparison" onClick={() => setShowComparison(false)}><X size={20} /></button></header><div className="table-scroll"><table><thead><tr><th>Endpoint</th>{selectedForCompare.map((rowNumber) => { const row = job.rows.find((item) => item.row_number === rowNumber)!; return <th key={rowNumber}>{row.compound_name ?? row.compound_id ?? `Row ${rowNumber}`}</th>; })}</tr></thead><tbody>{selectedEndpoints.map((key) => <tr key={key}><th>{registry[key]?.display_name ?? key}<small><code>{key}</code></small></th>{selectedForCompare.map((rowNumber) => <td key={rowNumber}>{displayValue(endpointValue(job.rows.find((item) => item.row_number === rowNumber)!, key))}</td>)}</tr>)}</tbody></table></div></section> : null}
    <ScientificDisclaimer />
  </div>;
}
